server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml